version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: easyorder-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      my-network:
        aliases:
          - db

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: easyorder-api
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/db
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.jpa.show-sql: false
      spring.jpa.hibernate.ddl-auto: update
    ports:
      - "8080:8080"
    restart: always
    networks:
      my-network:
        aliases:
          - api

  ui:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: easyorder-ui
    ports:
      - "5173:5173"
    restart: always
    networks:
      my-network:
        aliases:
          - ui

networks:
  my-network:
    driver: bridge
